version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3100:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:Fatahbacha69@db.gwyprjjalyubmumoegqa.supabase.co:5432/postgres
    networks:
      - default

networks:
  default:
    driver: bridge
